version: "3"
services:
  ##################
  # Database
  ##################
  db:
    image: postgres:9.6.1
    environment:
      POSTGRES_PASSWORD: adminadmin
      POSTGRES_DB: office
    volumes:
      - dbdata:/var/lib/postgresql/data

  ##################
  # Imixs-Office-Worklfow
  ##################
  imixs-office:
    image: imixs/imixs-office-workflow:latest
    depends_on:
      - db
    environment:
      JAVA_OPTS: "-Dnashorn.args=--no-deprecation-warning"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "adminadmin"
      POSTGRES_CONNECTION: "jdbc:postgresql://db/office"
      TZ: "Europe/Berlin"
      MAILGATEWAY: "localhost"
    ports:
      - "8080:8080"
      - "8787:8787"
      - "9990:9990"

  ##################
  # Exporter Service
  ##################
  imixsexporter-app:
    image: imixs/imixs-archive-exporter:latest
    environment:
      WILDFLY_PASS: adminadmin
      DEBUG: "true"

      # EXAMPLE SETUP
      WORKFLOW_SERVICE_ENDPOINT: "http://imixs-office:8080/api"
      WORKFLOW_SERVICE_USER: "dataservice"
      WORKFLOW_SERVICE_PASSWORD: "adminadmin"
      WORKFLOW_SERVICE_AUTHMETHOD: "form"

      METRICS_ENDPOINT: "http://localhost:9991/metrics"
      HEALTH_ENDPOINT: "http://localhost:9991/health"
      # Optional FTP Export
      #EXPORT_FTP_HOST: "ftp.storage.foo"
      #EXPORT_FTP_PATH: "/test/export-service/"
      #EXPORT_FTP_PORT: "21"
      #EXPORT_FTP_USER: ""
      #EXPORT_FTP_PASSWORD: ""
      EXPORT_PATH: "/opt/jboss/wildfly/test-export"
    ports:
      - "8081:8080"
      - "8788:8787"
      - "9991:9990"
    volumes:
      - ./imixs-archive-exporter/docker/deployments:/opt/jboss/wildfly/standalone/deployments/

  ##################
  # Backup Service
  ##################
  imixsbackup-app:
    image: imixs/imixs-archive-backup:latest
    environment:
      WILDFLY_PASS: adminadmin
      DEBUG: "true"

      # EXAMPLE SETUP
      WORKFLOW_SERVICE_ENDPOINT: "http://imixs-office:8080/api"
      WORKFLOW_SERVICE_USER: "dataservice"
      WORKFLOW_SERVICE_PASSWORD: "adminadmin"
      WORKFLOW_SERVICE_AUTHMETHOD: "form"

      EXPORT_FTP_HOST: "ftp.storage.foo"
      EXPORT_FTP_PATH: "/test/backup-service"
      EXPORT_FTP_PORT: "21"
      EXPORT_FTP_USER: ""
      EXPORT_FTP_PASSWORD: ""

      METRICS_ENDPOINT: "http://localhost:9992/metrics"
      HEALTH_ENDPOINT: "http://localhost:9992/health"
    ports:
      - "8082:8080"
      - "8789:8787"
      - "9992:9990"
    volumes:
      - ./imixs-archive-backup/docker/deployments:/opt/jboss/wildfly/standalone/deployments/

  ##################
  # Admin Client
  ##################
  imixsadmin:
    image: imixs/imixs-admin
    ports:
      - "8888:8080"

volumes:
  dbdata:
