postgresofficehadoop:
  image: postgres:9.6.1
  environment:
    POSTGRES_PASSWORD: adminadmin
    POSTGRES_DB: office

imixsofficeworkflowhadoop:
  image: imixs/imixs-office-workflow
  environment:
    WILDFLY_PASS: adminadmin
    DEBUG: "true"
  ports:
    - "8080:8080"
    - "9990:9990"
    - "8787:8787"
  links: 
    - postgresofficehadoop:postgres
  volumes:
      - ~/git/imixs-office-workflow/src/docker/.deployments:/opt/wildfly/standalone/deployments/
    