version: "3.1"
services:

  imixsarchiveservice:
    image: imixs/imixs-archive-service
   # depends_on:
   #   - imixsofficeworkflow
    environment:
      WILDFLY_PASS: adminadmin
      DEBUG: "true"
      ARCHIVE_CLUSTER_CONTACTPOINTS: "cassandra"
      ARCHIVE_CLUSTER_KEYSPACE: "imixsdev"
      ARCHIVE_SCHEDULER_DEFINITION: "hour=*;minute=*"
      WORKFLOW_SERVICE_ENDPOINT: http://imixsofficeworkflow:8080/api
      WORKFLOW_SERVICE_USER: "admin"
      WORKFLOW_SERVICE_PASSWORD: "adminadmin"
      WORKFLOW_SERVICE_AUTHMETHOD: "form"
      TZ: "Europe/Berlin"
      # JAVA_OPTS: "-Xms512m -Xmx1g -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=$JBOSS_MODULES_SYSTEM_PKGS -Djava.awt.headless=true"
      # ARCHIVE_CLUSTER_REPLICATION_FACTOR: "1"
      # ARCHIVE_CLUSTER_REPLICATION_CLASS: "SimpleStrategy"
      
    ports:
      - "8080:8080"
      - "9990:9990"
      - "8787:8787"
 #   volumes:
 #       - ~/git/imixs-archive/imixs-archive-service/src/docker/deployments:/opt/wildfly/standalone/deployments/
        
  #