version: "3.1"
services:

  imixsofficeworkflow:
    image: imixs/imixs-office-workflow:3.4.1-SNAPSHOT
    environment:
      WILDFLY_PASS: adminadmin
      DEBUG: "true"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "adminadmin"
      POSTGRES_CONNECTION: "jdbc:postgresql://postgresoffice/office"
    ports:
      - "8081:8080"
      - "9991:9990"
      - "8788:8787"     


  imixsarchiveservice:
    image: imixs/imixs-archive-service
    depends_on:
      - imixsofficeworkflow
    environment:
      WILDFLY_PASS: adminadmin
      DEBUG: "true"
      ARCHIVE_CLUSTER_CONTACTPOINTS: "cassandra"
      ARCHIVE_CLUSTER_KEYSPACE: "imixsdev"
    ports:
      - "8080:8080"
      - "9990:9990"
      - "8787:8787"
    volumes:
        - ~/git/imixs-archive/imixs-archive-service/src/docker/deployments:/opt/wildfly/standalone/deployments/
        
        
  cassandra:
     image: cassandra:3.11

     
  postgresoffice:
    image: postgres:9.6.1
    environment:
      POSTGRES_PASSWORD: adminadmin
      POSTGRES_DB: office



  imixsadmin:
    image: imixs/imixs-admin
    ports:
      - "8888:8080"
    