version: "3.1"
services:

  imixsarchiveservice:
    image: imixs/imixs-archive-service
    environment:
      WILDFLY_PASS: adminadmin
      DEBUG: "true"
      ARCHIVE_CLUSTER_CONTACTPOINTS: "cassandra"
      ARCHIVE_CLUSTER_KEYSPACE: "imixsdev"
    ports:
      - "8080:8080"
      - "9990:9990"
      - "8787:8787"
    volumes:
        - ~/git/imixs-archive/imixs-archive-service/src/docker/deployments:/opt/wildfly/standalone/deployments/

  cassandra:
     image: cassandra:3.11
