version: "3.1"
services:

  imixsofficeworkflow:
    image: imixs/imixs-office-workflow
    environment:
      WILDFLY_PASS: adminadmin
      DEBUG: "true"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "adminadmin"
      POSTGRES_CONNECTION: "jdbc:postgresql://postgresoffice/office"
      ARCHIVE_SERVICE_ENDPOINT: http://imixsarchiveservice:8080/api
      #ARCHIVE_SERVICE_USER: "admin"
      #ARCHIVE_SERVICE_PASSWORD: "adminadmin"
      #ARCHIVE_SERVICE_AUTHMETHOD: "form"
      TZ: "Europe/Berlin"  
    ports:
      - "8081:8080"
      - "9991:9990"
      - "8788:8787"     



  imixsarchiveservice:
    image: imixs/imixs-archive-service
    depends_on:
      - imixsofficeworkflow
      - cassandra
    environment:
      WILDFLY_PASS: adminadmin
      DEBUG: "true"
      ARCHIVE_CLUSTER_CONTACTPOINTS: "cassandra"
      ARCHIVE_CLUSTER_KEYSPACE: "imixsdev"
      ARCHIVE_SCHEDULER_DEFINITION: "hour=*;minute=*"
      EXPORT_SCHEDULER_DEFINITION: "hour=*"
      WORKFLOW_SERVICE_ENDPOINT: http://imixsofficeworkflow:8080/api
      WORKFLOW_SERVICE_USER: "admin"
      WORKFLOW_SERVICE_PASSWORD: "adminadmin"
      WORKFLOW_SERVICE_AUTHMETHOD: "form"
      TZ: "Europe/Berlin"
      
    ports:
      - "8080:8080"
      - "9990:9990"
      - "8787:8787"
    volumes:
        - ~/git/imixs-archive/imixs-archive-service/src/docker/deployments:/opt/wildfly/standalone/deployments/
        
        
  cassandra:
     image: cassandra:3.11

     
  postgresoffice:
    image: postgres:9.6.1
    environment:
      POSTGRES_PASSWORD: adminadmin
      POSTGRES_DB: office
    volumes: 
      - dbdata:/var/lib/postgresql/data


  imixsadmin:
    image: imixs/imixs-admin
    ports:
      - "8888:8080"
      
      
      
#  prometheus:
#    image: prom/prometheus
#    ports:
#      - "9090:9090"
#    volumes:
#      - ~/git/imixs-archive/imixs-archive-service/src/docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml 
  
#  grafana:
#    image: grafana/grafana
#    ports: 
#      - "3000:3000" 
  
volumes:
  dbdata:          
    