version: "3.1"
services:

  db:
    image: postgres:9.6.1
    environment:
      POSTGRES_PASSWORD: adminadmin
      POSTGRES_DB: office

  imixsofficeworkflow:
    image: imixs/imixs-office-workflow:3.2.1-SNAPSHOT
    environment:
      WILDFLY_PASS: adminadmin
      DEBUG: "true"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "adminadmin"
      POSTGRES_CONNECTION: "jdbc:postgresql://db/office"
    ports:
      - "8080:8080"
      - "9990:9990"
      - "8787:8787"

  cassandra:
     image: cassandra:3.11
     ports: 
      - "9042:9042" 