version: "3.1"
services:

     
  postgresoffice:
    image: postgres:9.6.1
    environment:
      POSTGRES_PASSWORD: adminadmin
      POSTGRES_DB: office

  imixsofficeworkflow:
    image: imixs/imixs-office-workflow:3.3.2-SNAPSHOT
    environment:
      WILDFLY_PASS: adminadmin
      DEBUG: "true"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "adminadmin"
      POSTGRES_CONNECTION: "jdbc:postgresql://postgresoffice/office"
    ports:
      - "8081:8080"
      - "9991:9990"
      - "8788:8787"     
